locations = [
    "Dallas Regional",
    "Lake Superior Regional",
    "Northern Lights Regional",
    "Palmetto Regional",
    "South Florida Regional",
    "Georgia Southern Classic Regional",
    "Inland Empire Regional",
    "FIM District – Howell Event",
    "FIM District – Southfield Event",
    "FIM District – Standish Event",
    "NE District – Granite State Event",
    "PNW District – Auburn Mountainview Event",
    "PNW District – Oregon City Event",
    "IN District – Indianapolis Event",
    "MAR District – Hatboro-Horsham Event",
    "NE District – Waterbury Event",
    "Arkansas Rock City Regional",
    "Greater Pittsburgh Regional",
    "Greater Toronto Central Regional",
    "Mexico City Regional",
    "Central Valley Regional",
    "FIM District – Kentwood Event",
    "FIM District – Kettering University Event",
    "FIM District – Waterford Event",
    "NE District – Pioneer Valley Event",
    "PNW District – West Valley Event",
    "MAR District – Mt. Olive Event",
    "NE District – Reading Event",
    "PNW District – Glacier Peak Event",
    "Israel Regional",
    "Alamo Regional",
    "Australia Regional",
    "Greater Kansas City Regional",
    "Greater Toronto East Regional",
    "Los Angeles Regional",
    "Orlando Regional",
    "Utah Regional",
    "New York City Regional",
    "FIM District – Gull Lake Event",
    "FIM District – Traverse City Event",
    "FIM District – Woodhaven Event",
    "IN District – Kokomo City of Firsts Event",
    "MAR District – Springside Chestnut Hill Event",
    "NE District – Pine Tree Event",
    "NE District – UMass – Dartmouth Event",
    "PNW District – Wilsonville Event",
    "PNW District – Mount Vernon Event",
    "Arizona East Regional",
    "Bayou Regional",
    "Central Illinois Regional",
    "Festival de Robotique – Montreal Regional",
    "New York Tech Valley Regional",
    "North Carolina Regional",
    "Sacramento Regional",
    "St. Louis Regional",
    "Virginia Regional",
    "Waterloo Regional",
    "Wisconsin Regional",
    "FIM District – Great Lakes Bay Region Event",
    "FIM District – St. Joseph Event",
    "FIM District – West Michigan Event",
    "IN District – Purdue Event",
    "PNW District – Central Washington University Event",
    "MAR District – Seneca Event",
    "NE District – Rhode Island Event",
    "NE District – UNH Event",
    "PNW District – Shorewood Event",
    "Buckeye Regional",
    "Colorado Regional",
    "Finger Lakes Regional",
    "Greater DC Regional",
    "Hawaii Regional",
    "Hub City Regional",
    "Las Vegas Regional",
    "North Bay Regional",
    "Oklahoma Regional",
    "Peachtree Regional",
    "SBPLI Long Island Regional",
    "Ventura Regional",
    "Championship",
    "FIM District – Center Line Event",
    "FIM District – Escanaba Event",
    "FIM District – Livonia Event",
    "NE District – Northeastern University Event",
    "PNW District – Auburn Event",
    "PNW District – Philomath Event",
    "MAR District – Bridgewater-Raritan Event",
    "MAR District – Upper Darby Event",
    "NE District – Hartford Event",
    "Arizona West Regional",
    "Chesapeake Regional",
    "Lone Star Regional",
    "Midwest Regional",
    "Minnesota 10,000 Lakes Regional",
    "Minnesota North Star Regional",
    "Queen City Regional",
    "San Diego Regional",
    "Silicon Valley Regional",
    "Smoky Mountains Regional",
    "Western Canada Regional",
    "Windsor Essex Great Lakes Regional",
    "Pacific Northwest District Championship",
    "District Championship",
    "FIM District – Bedford Event",
    "FIM District – Lansing Event",
    "FIM District – Troy Event",
    "MAR District – North Brunswick Event",
    "in Michigan District Championship",
    "Mid-Atlantic Robotics District Championship",
    "NE FIRST District Championship"
]
